### ISSUE TITLE
Add Jekyll Plugin to improve SEO

### ISSUE THREAD

**Issue by exactlyallan** [rapidsai/rapids.ai#154]
Google console is showing some errors that will downgrade Rapids.ai SEO (e.g. preview card url is missing)

 I found this plugin that will help fix some of the issues (looks fairly harmless): https://jekyll.github.io/jekyll-seo-tag/

Does it seem like something we can add or should we implement on our own?

**Comment by aravenel** [comment]
Refactoring website (see #242); will no longer be using Jekyll. Closing as wontfix.
