### ISSUE TITLE
Update System Requirements on Start page to reflect CUDA Compatibility

### ISSUE THREAD

**Issue by beckernick** [rapidsai/rapids.ai#236]
Many of our users are not systems programmers nor are they well versed in the CUDA ecosystem. When they see images like this:

![image](https://user-images.githubusercontent.com/8457388/187229418-a5c527cb-6e53-461e-bf6d-ba5337af39c0.png)

They do not realize they can select a different version than their system's installed version. This has come up with both internal and external users, who get confused when trying to install RAPIDS with other CUDA projects like Tensorflow.

We shouldn't re-explain CUDA Compatibility, but we should inform users that RAPIDS does not need a minor version that exactly matches their system's version. In the vast majority of scenarios, things will work without issue.

**Comment by exactlyallan** [comment]
Should be handled in https://docs.rapids.ai/install now
