### ISSUE TITLE
Refactor RAPIDS Website and User Experience

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/rapids.ai#242]
The website needs refactoring!  

VDR Action Items for 22.10 https://docs.google.com/spreadsheets/d/1qNLnDGmuC2bdWKe8CBnZ3h9TNVi5aEg5GBnYZoQ82d0/edit#gid=1127620981

Initial reasoning and proposal: https://nvidia-my.sharepoint.com/:p:/r/personal/tdyer_nvidia_com/Documents/RAPIDS%20Website%20Updates.pptx?d=w176271161772455483a6eac6df97b22a&csf=1&web=1&e=bHCI37

Current refactoring plan: https://docs.google.com/document/d/1nI625HC8MqCJFuZCDnFCH8Q5bJ1EQ3A-O2ldhVON6TU/edit#

Draft visuals: https://github.com/rapidsai/rapids.ai/pull/194

**Comment by exactlyallan** [comment]
done with https://github.com/rapidsai/rapids.ai/pull/289
