### ISSUE TITLE
Miscellaneous Long Term Website Thoughts

### ISSUE THREAD

**Issue by ajschmidt8** [rapidsai/rapids.ai#244]
Created this issue as a spot for @exactlyallan and I to record some long-term ideas for the main website and docs website.

- Remove redundant / extraneous content on docs site
- Simplifying existing content types
  - RAPIDS Notices:
    - should they live on the docs site? They're not technically documentation. Presumably more people visit our main site, so they should potentially be posted there instead
    - the content types seem overly complex. They're effectively just an announcement. But they have several confusing choices that need be made upon publishing such as:
      - Should this be a Developer, General, or Support notice
      - Is it a Proposal, Completed, In Progress, or Closed?
      - Should it be pinned to the "Recent and Important Notices" section
      - What is the Topic?
- Maintain a historical archive of all, un-processed RAPIDS documentation in several file formats (e.g. .txt, .pdf, .html)
  - We currently don't have a historical archive like this. We should probably have it for posterity. Ideally these docs would live in S3. Additionally, it would help with creating tools like the _RAPIDS Version Migration Assistant_ that Taurean and Allan are working on
  - Additionally, this would let us remove the API HTML files from the `docs` repo itself. There are currently tens of thousands of HTML files checked into that repository, which makes it extremely difficult to work with
    - Ideally, those HTML files would be stored externally (e.g. in S3) and pulled in at build time
    - Introducing a build time step would also mean we have to either:
      - Customize the [actions/deploy-pages](https://github.com/actions/deploy-pages) action for deploying to GitHub Pages (which is currently in `beta` at the time of writing)
      - Or switch to a different hosting service that gives us more control over building (like [S3](https://docs.aws.amazon.com/AmazonS3/latest/userguide/WebsiteHosting.html), [Netlify](https://www.netlify.com/), or [Render](https://render.com/))
        - Personally, this is what I think we should do
- Move off of Jekyll to [Hugo](https://gohugo.io/) for both the main website and docs website
- Consider moving anything that's not documentation from the docs website to the main website

**Comment by exactlyallan** [comment]
Proposed https://docs.rapids.ai/ home page top level site map update:

- Home
- Install Guide ( requirements and getting started selector moved here )
- User Guide ( 10min notebooks and library specific notebooks etc )
- Deployment Guides ( local, cloud, HPC, HPO etc )
- API / Library Documentation 
   - Add 'core rapids section'
   - Add 'extensions section' i.e. clx / cuxfilter
   - NOTE: finalize distinction between library, api, sdk, integration, extensions etc..._
- _REMOVE_: Notices (moved to rapids.ai, sourced from external db/csv)
- _REMOVE_: Demos (outdated)
- _REMOVE_? gpuCI (remove?)
- _REMOVE_? maintainers (move to github contribute?)
 
 
 _NOTE:_ Working towards Sphinx documentation standard and s3 raw docs architecture

**Comment by exactlyallan** [comment]
> * Move off of Jekyll to [Hugo](https://gohugo.io/) for both the main website and docs website
Fine for using Hugo for docs, still think no-build vanilla HTML for website. 

> * Consider moving anything that's not documentation from the docs website to the main website
Lets better define 'not documentation' - see above for my suggestions.
