### ISSUE TITLE
[DOC] Add list of quick start notebooks to Notebooks Repo readme and Getting Started/Docs site

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/rapids.ai#266]
I'll make a quick markdown listing all our intro notebooks that we can 

- [ ] add to getting started/install area
- [ ] the readme in notebooks repo
- [ ] add to any other needed area

Is there a way to have it "write once, copy everywhere" @exactlyallan?

https://github.com/rapidsai/rapids.ai/issues/266#tasklist-block-08bdf1b4-d5e0-4d6f-93b1-46ec9385a274

**Comment by exactlyallan** [comment]
done with https://github.com/rapidsai/rapids.ai/pull/289
