### ISSUE TITLE
[WIP] Polish site content and links for Docs Install and Site Latest News

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/rapids.ai#272]
- [ ] Docs Site:
  - [ ] Install RAPIDS
    - [ ] Install
      - [ ] On Machine
        - [ ] WSL2
        - [ ] Pip Experimental
      - [ ] Cloud Deploy
        - [ ] CSPs and special installs
        - [ ] Pre Installed 
    - [ ] User guide links 
      - [ ] cuDF  Library Basics
      - [ ] cuDF Guide
      - [ ] cuML Library Basics
      - [ ] cuML Guide
      - [ ] cuGraph Library Basics
      - [ ] cuGraph Guide
    - [ ] 10 minutes intro notebooks links #
    - [ ] next steps links
    - [ ] Blogs and Video List?
  - [ ] Switch from Jekyll to Hugo
- [ ] Main Site
  - [ ] Latest news
    - [ ] Industry Use cases
      - [ ] Work with Nick, WWFO, and the SA team on gathering use cases in the wild
      - [ ] Work with Paul on gathering research and bundling example notebooks
      - [ ] Work with Randy on getting workflows and some more real world benchmarks
      - [ ] Work with Data Science Blueprints, Hackathons, and other Notebook Contrib sources to give examples

**Comment by exactlyallan** [comment]
Done with https://github.com/rapidsai/rapids.ai/pull/289
