### ISSUE TITLE
Add mini benchmarks to site introduction

### ISSUE THREAD

**Issue by exactlyallan** [rapidsai/rapids.ai#276]
Ideally simple 2-3 category benchmark for cuDF, cuML, and cuGraph.

**Comment by KlokMiraj** [comment]
I'd like to solve this issue if up for grab :)

**Comment by taureandyernv** [comment]
Hey, @KlokMiraj happy for the community help and support.  Wanna [chat more on RAPIDS-Goai slack](https://join.slack.com/t/rapids-goai/shared_invite/zt-trnsul8g-Sblci8dk6dIoEeGpoFcFOQ)?

**Comment by exactlyallan** [comment]
cuML resolved with https://github.com/rapidsai/cuml/pull/5103

**Comment by exactlyallan** [comment]
cudf resolved with https://github.com/rapidsai/cudf/pull/12595

**Comment by exactlyallan** [comment]
cuGraph resolved with https://github.com/rapidsai/cugraph/pull/3135

**Comment by exactlyallan** [comment]
Working to run all benchmarks on similar DGX A100 machine - having difficulties completing runs becaus they take so long or jupyter cell seems to idle.

Completed:
- [ ] cuML
- [ ] cuGraph
- [ ] cuDF

**Comment by exactlyallan** [comment]
done with https://github.com/rapidsai/rapids.ai/pull/289
