### ISSUE TITLE
Add Ecosystem and Home page content

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/rapids.ai#279]
Tracking Copy Changes here:
https://docs.google.com/spreadsheets/d/1_gL2c_RXS987CAErFrmx1I9nmd__MtZmGOMe6YZszQo/edit#gid=1205829777

**Comment by robocopnixon** [comment]
When is the deadline?

**Comment by exactlyallan** [comment]
done with https://github.com/rapidsai/rapids.ai/pull/289
