### ISSUE TITLE
Reinstitute RAPIDS - Colab Try It Now section

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/rapids.ai#282]
RAPIDS try it Now once places again includes colab, with 2 ways to install:
- pip : https://colab.research.google.com/drive/13sspqiEZwso4NYTbsflpPyNFaVAAxUgr
- conda: https://colab.research.google.com/drive/1TAAi_szMfWqRfHVfjGSqnGVLr_ztzUM9

May we please add back the colab verbiage and graphic?  We should default to the PIP install colab notebook.
```[tasklist]
### Try It Now Section
- [ ] Add Colab image back by sagemaker studio
- [ ] Add pip template link 
- [ ] provide explanation that we're using pip, only has cudf, cuml, and cugraph, and if they want full functionality, use conda template
- [ ] provide conda template link
```
@exactlyallan @aravenel

**Comment by exactlyallan** [comment]
Done with https://github.com/rapidsai/rapids.ai/pull/289
