### ISSUE TITLE
Remove Asyc Content Fetching

### ISSUE THREAD

**Issue by exactlyallan** [rapidsai/rapids.ai#293]
Current method is broken. Building alternative to async content fetching.

e.g. [Twitter and Blog Posts](https://github.com/exactlyallan/rapids.ai/blob/2b244054c785a190abfdb71062126ac8d1f70cf6/layouts/shortcodes/post-tweets.html#L2-L15)).

**Comment by ajschmidt8** [comment]
Fixed in https://github.com/exactlyallan/rapids.ai/pull/2.

**Comment by ajschmidt8** [comment]
https://github.com/exactlyallan/rapids.ai/pull/2 was merged. Closing this issue.
