### ISSUE TITLE
Add Netlify link forwarding for outdated links

### ISSUE THREAD

**Issue by exactlyallan** [rapidsai/rapids.ai#299]
Add link forwarding for the following:

- [ ] https://rapids.ai/start.html -> https://docs.rapids.ai/install
- [ ] https://rapids.ai/wsl2.html -> https://docs.rapids.ai/install#WSL2
- [ ] https://rapids.ai/pip.html -> https://docs.rapids.ai/install#pip
- [ ] https://rapids.ai/dask.html -> https://docs.dask.org/en/stable/gpu.html
- [ ] https://rapids.ai/xgboost.html -> https://xgboost.readthedocs.io/en/stable/gpu/index.html
- [ ] https://rapids.ai/plotly.html -> https://docs.rapids.ai/visualization
- [ ] https://rapids.ai/hpo.html -> https://docs.rapids.ai/deployment/stable/examples/index.html
- [ ] https://rapids.ai/hpc -> https://docs.rapids.ai/deployment/stable/hpc.html
- [ ] https://rapids.ai/about.html -> https://rapids.ai/learn-more/#about
- [ ] https://rapids.ai/community.html -> https://rapids.ai/learn-more/#get-involved

**Comment by ajschmidt8** [comment]
@exactlyallan, done in https://github.com/exactlyallan/rapids.ai/pull/1.

There is a preview link in the PR comments.

Feel free to verify and merge that PR into your branch.
