### ISSUE TITLE
Add Twitter Feed Pull Script

### ISSUE THREAD

**Issue by exactlyallan** [rapidsai/rapids.ai#313]
Add a python script to automate twitter feed updates similar to blog posts here https://github.com/rapidsai/rapids.ai/tree/gh-pages/scripts - currently only a manual process and leads to the feed being outdated quickly. 

Is this actually still possible with twitter borking its API access lately? @ajschmidt8

**Comment by aravenel** [comment]
Yeah, I agree that its not worth $100/month to syndicate our own tweets. And it is unlikely that we would be able to get approval for the expenses anyways.

**Comment by exactlyallan** [comment]
Makes sense, Ill remove tweets from the site.
