### ISSUE TITLE
Add rmm to the selector

### ISSUE THREAD

**Issue by vyasr** [rapidsai/rapids.ai#320]
Currently rmm is not included explicitly on the website's main selector and it is assumed that it will always be installed implicitly as a dependency of other RAPIDS packages. Since there are [users who may wish to use rmm alone](https://github.com/rapidsai/rmm/issues/1253), it would be nice to add it to the selector.

**Comment by exactlyallan** [comment]
Being tracked here - https://github.com/rapidsai/docs/pull/409
