### ISSUE TITLE
[FEA]Add torch to the install selector tool

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/rapids.ai#340]
We should add torch to our installation selector tool here  https://docs.rapids.ai/install   .  

@jakirkham  and  team have made it now very easy to install pytorch+rapids  together  and we should allow users to take advantage of that.  (See internal [thread](https://nvidia.slack.com/archives/CLJS87RL1/p1699326108490939?thread_ts=1697491690.059729&cid=CLJS87RL1) for more details)

That is below works now:
```python3
mamba create -n cudf_torch -c rapidsai-nightly  -c conda-forge -c nvidia cudf=23.12 cuda-version=12.0 pytorch=2.0
```

**Comment by jakirkham** [comment]
> @jakirkham and team have made it now very easy to install pytorch+rapids together

_Much_ more emphasis on team than self 😉

<hr>

Glad to hear this is working! 🎉

**Comment by jarmak-nv** [comment]
This was completed in rapidsai/docs#450 :tada:

I can't close the issue tho, @VibhuJawa can you close please 🙏
